### ISSUE TITLE
10-27-2015: Downloading Videos from a XML/JSON Feed with Node and Elixir

### ISSUE THREAD

**Issue by blainsmith** [agnostechvalley/agnostechvalley.github.io#2]
**When:** October 27, 2015 @ 5:30
**Where:** MadGlory Office

For our first meetup we wanted to keep the problem trivial so we can focus on learning the languages itself. @rjsamson will be show us how he solved the problem in [Elixir](http://elixir-lang.org) and @brkattk will show us the same solution, but in [Node](https://nodejs.org).

The feeds we will be pulling from are running on https://private-feed-server.herokuapp.com which is a server I spun up for this problem and the [repo is available](https://github.com/agnostechvalley/private-feeds-server) to see how I did that.

Feel free to jot down questions here or even give a :+1: telling us you are coming so we can have a rough head count.

**Comment by richardardrichard** [comment]
:+1:

**Comment by vfrride** [comment]
Nice topic! I'm going to be out of town, but will enjoy reviewing the code!

**Comment by chiefy** [comment]
![](http://i.giphy.com/yrHFoyguQXSmI.gif)

**Comment by DanPallas** [comment]
:+1:

**Comment by doon** [comment]
:+1: looking forward to it

**Comment by blainsmith** [comment]
Thanks for coming out! Keep an eye out for next month's meetup time and create issues for new topics! Also tell more people!
